#!/usr/bin/env python3
"""
Custom protoc plugin that generates pure Python classes with JSON serialization.

Usage:
    protoc --plugin=protoc-gen-pyjson=./protoc-gen-pyjson \
           --pyjson_out=./output \
           your_file.proto
"""

import sys
from typing import Dict, List, Optional, Set
from google.protobuf.compiler import plugin_pb2 as plugin
from google.protobuf.descriptor_pb2 import (
    FileDescriptorProto,
    DescriptorProto,
    FieldDescriptorProto,
    EnumDescriptorProto,
)


PROTO_TYPE_TO_PYTHON = {
    FieldDescriptorProto.TYPE_DOUBLE: "float",
    FieldDescriptorProto.TYPE_FLOAT: "float",
    FieldDescriptorProto.TYPE_INT64: "int",
    FieldDescriptorProto.TYPE_UINT64: "int",
    FieldDescriptorProto.TYPE_INT32: "int",
    FieldDescriptorProto.TYPE_FIXED64: "int",
    FieldDescriptorProto.TYPE_FIXED32: "int",
    FieldDescriptorProto.TYPE_BOOL: "bool",
    FieldDescriptorProto.TYPE_STRING: "str",
    FieldDescriptorProto.TYPE_BYTES: "bytes",
    FieldDescriptorProto.TYPE_UINT32: "int",
    FieldDescriptorProto.TYPE_SFIXED32: "int",
    FieldDescriptorProto.TYPE_SFIXED64: "int",
    FieldDescriptorProto.TYPE_SINT32: "int",
    FieldDescriptorProto.TYPE_SINT64: "int",
}

# Default values for proto types
PROTO_TYPE_DEFAULTS = {
    FieldDescriptorProto.TYPE_DOUBLE: "0.0",
    FieldDescriptorProto.TYPE_FLOAT: "0.0",
    FieldDescriptorProto.TYPE_INT64: "0",
    FieldDescriptorProto.TYPE_UINT64: "0",
    FieldDescriptorProto.TYPE_INT32: "0",
    FieldDescriptorProto.TYPE_FIXED64: "0",
    FieldDescriptorProto.TYPE_FIXED32: "0",
    FieldDescriptorProto.TYPE_BOOL: "False",
    FieldDescriptorProto.TYPE_STRING: '""',
    FieldDescriptorProto.TYPE_BYTES: 'b""',
    FieldDescriptorProto.TYPE_UINT32: "0",
    FieldDescriptorProto.TYPE_SFIXED32: "0",
    FieldDescriptorProto.TYPE_SFIXED64: "0",
    FieldDescriptorProto.TYPE_SINT32: "0",
    FieldDescriptorProto.TYPE_SINT64: "0",
}


class CodeGenerator:
    """Generates Python code for protobuf messages."""

    def __init__(self, proto_file: FileDescriptorProto, all_files: Dict[str, FileDescriptorProto]):
        self.proto_file = proto_file
        self.all_files = all_files
        self.package = proto_file.package
        self.indent = "    "
        self.imports: Set[str] = set()
        self.message_map: Dict[str, str] = {}  # full proto name -> Python class name
        self._build_message_map()

    def _build_message_map(self):
        """Build a mapping of proto type names to Python class names."""
        def add_messages(messages: List[DescriptorProto], prefix: str, py_prefix: str):
            for msg in messages:
                full_name = f"{prefix}.{msg.name}"
                py_name = f"{py_prefix}{msg.name}" if py_prefix else msg.name
                self.message_map[full_name] = py_name
                # Handle nested messages
                add_messages(msg.nested_type, full_name, f"{py_name}.")

        # Build map for current file
        pkg_prefix = f".{self.package}" if self.package else ""
        add_messages(self.proto_file.message_type, pkg_prefix, "")

        # Build map for all imported files
        for dep_name in self.proto_file.dependency:
            if dep_name in self.all_files:
                dep_file = self.all_files[dep_name]
                dep_pkg = f".{dep_file.package}" if dep_file.package else ""
                add_messages(dep_file.message_type, dep_pkg, "")

    def generate(self) -> str:
        """Generate the complete Python module."""
        lines = []

        # Module docstring
        lines.append(f'"""')
        lines.append(f"Generated from {self.proto_file.name}")
        lines.append(f"DO NOT EDIT - generated by protoc-gen-otlp_json")
        lines.append(f'"""')
        lines.append("")

        # Generate enums first
        enum_code = self._generate_enums(self.proto_file.enum_type)

        # Generate messages
        message_code = self._generate_messages(self.proto_file.message_type)

        # Now add imports (collected during generation)
        lines.append("from __future__ import annotations")
        lines.append("")
        lines.append("import json")
        lines.append("import base64")
        lines.append("from dataclasses import dataclass, field")
        lines.append("from typing import Any, Dict, List, Optional, Type, TypeVar")
        lines.append("from enum import IntEnum")
        lines.append("")

        # Add helper base class
        lines.append(self._generate_base_class())
        lines.append("")

        # Add enum and message code
        lines.append(enum_code)
        lines.append(message_code)

        return "\n".join(lines)

    def _generate_base_class(self) -> str:
        """Generate the base class with JSON serialization helpers."""
        return '''
T = TypeVar("T", bound="ProtoMessage")


class ProtoMessage:
    """Base class for all generated protobuf messages."""

    def to_dict(self) -> Dict[str, Any]:
        """Convert message to a dictionary."""
        raise NotImplementedError

    def to_json(self, indent: Optional[int] = None) -> str:
        """Serialize message to JSON string."""
        return json.dumps(self.to_dict(), indent=indent)

    @classmethod
    def from_dict(cls: Type[T], data: Dict[str, Any]) -> T:
        """Create message from a dictionary."""
        raise NotImplementedError

    @classmethod
    def from_json(cls: Type[T], json_str: str) -> T:
        """Deserialize message from JSON string."""
        return cls.from_dict(json.loads(json_str))
'''

    def _generate_enums(self, enums: List[EnumDescriptorProto], indent: int = 0) -> str:
        """Generate Python IntEnum classes for proto enums."""
        lines = []
        prefix = self.indent * indent

        for enum in enums:
            lines.append(f"{prefix}class {enum.name}(IntEnum):")
            if not enum.value:
                lines.append(f"{prefix}{self.indent}pass")
            else:
                for value in enum.value:
                    lines.append(f"{prefix}{self.indent}{value.name} = {value.number}")
            lines.append("")

        return "\n".join(lines)

    def _generate_messages(self, messages: List[DescriptorProto], indent: int = 0) -> str:
        """Generate Python dataclasses for proto messages."""
        lines = []
        prefix = self.indent * indent

        for message in messages:
            # Generate nested enums first
            if message.enum_type:
                lines.append(self._generate_enums(message.enum_type, indent))

            # Generate nested messages
            if message.nested_type:
                # Filter out map entry types (synthetic messages for map fields)
                non_map_nested = [m for m in message.nested_type if not m.options.map_entry]
                if non_map_nested:
                    lines.append(self._generate_messages(non_map_nested, indent))

            # Start message class
            lines.append(f"{prefix}@dataclass")
            lines.append(f"{prefix}class {message.name}(ProtoMessage):")

            # Check for map fields
            map_fields = self._get_map_fields(message)

            # Generate fields
            fields = []
            for field in message.field:
                field_code = self._generate_field(field, message, map_fields, indent + 1)
                fields.append(field_code)

            if not fields:
                lines.append(f"{prefix}{self.indent}pass")
            else:
                lines.extend(fields)

            lines.append("")

            # Generate to_dict method
            lines.append(self._generate_to_dict(message, map_fields, indent + 1))
            lines.append("")

            # Generate from_dict method
            lines.append(self._generate_from_dict(message, map_fields, indent + 1))
            lines.append("")

        return "\n".join(lines)

    def _get_map_fields(self, message: DescriptorProto) -> Dict[str, DescriptorProto]:
        """Identify map fields by finding their synthetic entry types."""
        map_fields = {}
        entry_types = {m.name: m for m in message.nested_type if m.options.map_entry}

        for field in message.field:
            if field.type == FieldDescriptorProto.TYPE_MESSAGE:
                type_name = field.type_name.split(".")[-1]
                if type_name in entry_types:
                    map_fields[field.name] = entry_types[type_name]

        return map_fields

    def _generate_field(
        self,
        field: FieldDescriptorProto,
        message: DescriptorProto,
        map_fields: Dict[str, DescriptorProto],
        indent: int,
    ) -> str:
        """Generate a dataclass field."""
        prefix = self.indent * indent
        name = field.name
        is_repeated = field.label == FieldDescriptorProto.LABEL_REPEATED

        # Handle map fields
        if name in map_fields:
            entry = map_fields[name]
            key_field = next(f for f in entry.field if f.name == "key")
            value_field = next(f for f in entry.field if f.name == "value")
            key_type = self._get_python_type(key_field)
            value_type = self._get_python_type(value_field)
            return f"{prefix}{name}: Dict[{key_type}, {value_type}] = field(default_factory=dict)"

        python_type = self._get_python_type(field)

        if is_repeated:
            return f"{prefix}{name}: List[{python_type}] = field(default_factory=list)"
        elif field.type == FieldDescriptorProto.TYPE_MESSAGE:
            return f"{prefix}{name}: Optional[{python_type}] = None"
        elif field.type == FieldDescriptorProto.TYPE_ENUM:
            # Get the enum's first value as default
            return f"{prefix}{name}: {python_type} = 0"
        else:
            default = PROTO_TYPE_DEFAULTS.get(field.type, "None")
            return f"{prefix}{name}: {python_type} = {default}"

    def _get_python_type(self, field: FieldDescriptorProto) -> str:
        """Get the Python type for a proto field."""
        if field.type in PROTO_TYPE_TO_PYTHON:
            return PROTO_TYPE_TO_PYTHON[field.type]
        elif field.type == FieldDescriptorProto.TYPE_ENUM:
            # Extract enum name from type_name
            return field.type_name.split(".")[-1]
        elif field.type == FieldDescriptorProto.TYPE_MESSAGE:
            # Extract message name from type_name
            type_name = field.type_name.split(".")[-1]
            return type_name
        else:
            return "Any"

    def _generate_to_dict(
        self, message: DescriptorProto, map_fields: Dict[str, DescriptorProto], indent: int
    ) -> str:
        """Generate the to_dict method."""
        prefix = self.indent * indent
        inner = self.indent * (indent + 1)
        lines = [f"{prefix}def to_dict(self) -> Dict[str, Any]:"]
        lines.append(f'{inner}"""Convert to dictionary for JSON serialization."""')
        lines.append(f"{inner}result: Dict[str, Any] = {{}}")

        for field in message.field:
            name = field.name
            is_repeated = field.label == FieldDescriptorProto.LABEL_REPEATED

            # Handle map fields
            if name in map_fields:
                entry = map_fields[name]
                value_field = next(f for f in entry.field if f.name == "value")
                if value_field.type == FieldDescriptorProto.TYPE_MESSAGE:
                    lines.append(
                        f"{inner}if self.{name}:"
                    )
                    lines.append(
                        f"{inner}{self.indent}result['{name}'] = {{k: v.to_dict() for k, v in self.{name}.items()}}"
                    )
                else:
                    lines.append(f"{inner}if self.{name}:")
                    lines.append(f"{inner}{self.indent}result['{name}'] = dict(self.{name})")
                continue

            if is_repeated:
                if field.type == FieldDescriptorProto.TYPE_MESSAGE:
                    lines.append(f"{inner}if self.{name}:")
                    lines.append(
                        f"{inner}{self.indent}result['{name}'] = [item.to_dict() for item in self.{name}]"
                    )
                elif field.type == FieldDescriptorProto.TYPE_BYTES:
                    lines.append(f"{inner}if self.{name}:")
                    lines.append(
                        f"{inner}{self.indent}result['{name}'] = [base64.b64encode(item).decode('utf-8') for item in self.{name}]"
                    )
                elif field.type == FieldDescriptorProto.TYPE_ENUM:
                    lines.append(f"{inner}if self.{name}:")
                    lines.append(f"{inner}{self.indent}result['{name}'] = [int(item) for item in self.{name}]")
                else:
                    lines.append(f"{inner}if self.{name}:")
                    lines.append(f"{inner}{self.indent}result['{name}'] = list(self.{name})")
            elif field.type == FieldDescriptorProto.TYPE_MESSAGE:
                lines.append(f"{inner}if self.{name} is not None:")
                lines.append(f"{inner}{self.indent}result['{name}'] = self.{name}.to_dict()")
            elif field.type == FieldDescriptorProto.TYPE_BYTES:
                lines.append(f"{inner}if self.{name}:")
                lines.append(
                    f"{inner}{self.indent}result['{name}'] = base64.b64encode(self.{name}).decode('utf-8')"
                )
            elif field.type == FieldDescriptorProto.TYPE_ENUM:
                lines.append(f"{inner}if self.{name}:")
                lines.append(f"{inner}{self.indent}result['{name}'] = int(self.{name})")
            else:
                default = PROTO_TYPE_DEFAULTS.get(field.type, "None")
                # Only include non-default values for scalars
                if field.type == FieldDescriptorProto.TYPE_BOOL:
                    lines.append(f"{inner}if self.{name}:")
                    lines.append(f"{inner}{self.indent}result['{name}'] = self.{name}")
                elif field.type in (FieldDescriptorProto.TYPE_STRING,):
                    lines.append(f"{inner}if self.{name}:")
                    lines.append(f"{inner}{self.indent}result['{name}'] = self.{name}")
                else:
                    lines.append(f"{inner}if self.{name} != {default}:")
                    lines.append(f"{inner}{self.indent}result['{name}'] = self.{name}")

        lines.append(f"{inner}return result")
        return "\n".join(lines)

    def _generate_from_dict(
        self, message: DescriptorProto, map_fields: Dict[str, DescriptorProto], indent: int
    ) -> str:
        """Generate the from_dict class method."""
        prefix = self.indent * indent
        inner = self.indent * (indent + 1)
        lines = [f"{prefix}@classmethod"]
        lines.append(f'{prefix}def from_dict(cls, data: Dict[str, Any]) -> "{message.name}":')
        lines.append(f'{inner}"""Create instance from dictionary."""')

        # Build kwargs for constructor
        lines.append(f"{inner}kwargs: Dict[str, Any] = {{}}")

        for field in message.field:
            name = field.name
            is_repeated = field.label == FieldDescriptorProto.LABEL_REPEATED

            lines.append(f'{inner}if "{name}" in data:')

            # Handle map fields
            if name in map_fields:
                entry = map_fields[name]
                value_field = next(f for f in entry.field if f.name == "value")
                if value_field.type == FieldDescriptorProto.TYPE_MESSAGE:
                    value_type = value_field.type_name.split(".")[-1]
                    lines.append(
                        f"{inner}{self.indent}kwargs['{name}'] = {{k: {value_type}.from_dict(v) for k, v in data['{name}'].items()}}"
                    )
                else:
                    lines.append(f"{inner}{self.indent}kwargs['{name}'] = dict(data['{name}'])")
                continue

            if is_repeated:
                if field.type == FieldDescriptorProto.TYPE_MESSAGE:
                    type_name = field.type_name.split(".")[-1]
                    lines.append(
                        f"{inner}{self.indent}kwargs['{name}'] = [{type_name}.from_dict(item) for item in data['{name}']]"
                    )
                elif field.type == FieldDescriptorProto.TYPE_BYTES:
                    lines.append(
                        f"{inner}{self.indent}kwargs['{name}'] = [base64.b64decode(item) for item in data['{name}']]"
                    )
                elif field.type == FieldDescriptorProto.TYPE_ENUM:
                    enum_name = field.type_name.split(".")[-1]
                    lines.append(
                        f"{inner}{self.indent}kwargs['{name}'] = [{enum_name}(item) for item in data['{name}']]"
                    )
                else:
                    lines.append(f"{inner}{self.indent}kwargs['{name}'] = list(data['{name}'])")
            elif field.type == FieldDescriptorProto.TYPE_MESSAGE:
                type_name = field.type_name.split(".")[-1]
                lines.append(
                    f"{inner}{self.indent}kwargs['{name}'] = {type_name}.from_dict(data['{name}'])"
                )
            elif field.type == FieldDescriptorProto.TYPE_BYTES:
                lines.append(
                    f"{inner}{self.indent}kwargs['{name}'] = base64.b64decode(data['{name}'])"
                )
            elif field.type == FieldDescriptorProto.TYPE_ENUM:
                enum_name = field.type_name.split(".")[-1]
                lines.append(f"{inner}{self.indent}kwargs['{name}'] = {enum_name}(data['{name}'])")
            else:
                lines.append(f"{inner}{self.indent}kwargs['{name}'] = data['{name}']")

        lines.append(f"{inner}return cls(**kwargs)")
        return "\n".join(lines)


def generate_code(request: plugin.CodeGeneratorRequest) -> plugin.CodeGeneratorResponse:
    """Process the code generation request."""
    response = plugin.CodeGeneratorResponse()
    response.supported_features = plugin.CodeGeneratorResponse.FEATURE_PROTO3_OPTIONAL

    # Build a map of all file descriptors
    all_files = {f.name: f for f in request.proto_file}

    # Process each file that was explicitly requested
    for file_name in request.file_to_generate:
        proto_file = all_files[file_name]

        # Skip files with no messages or enums
        if not proto_file.message_type and not proto_file.enum_type:
            continue

        # Generate Python code
        generator = CodeGenerator(proto_file, all_files)
        code = generator.generate()

        # Create output file
        output_file = response.file.add()
        output_file.name = file_name.replace(".proto", ".py")
        output_file.content = code

    return response


def main():
    """Main entry point."""
    # Read request from stdin
    data = sys.stdin.buffer.read()
    request = plugin.CodeGeneratorRequest()
    request.ParseFromString(data)

    # Generate response
    response = generate_code(request)

    # Write response to stdout
    sys.stdout.buffer.write(response.SerializeToString())


if __name__ == "__main__":
    main()